export const site = {
  name: "Youssef Saleh",
  role: "Software Engineer",
  brief:
    "Full-Stack Developer skilled in React.js, Next.js, Node.js, NestJS, and Java Spring Boot, experienced in building scalable web applications, REST APIs, and responsive UIs with clean, maintainable code.",
  email: "yousseffmohamedd22@gmail.com",
  location: "Remote / Worldwide",
  availability: "Open for select projects",
  nav: [
    { label: "Work", href: "#work" },
    { label: "Previous", href: "#previous" },
    { label: "About", href: "#about" },
    { label: "Skills", href: "#skills" },
    { label: "Contact", href: "#contact" },
  ],
  socials: [
    { label: "GitHub", href: "https://github.com/yousseffninja" },
    { label: "LinkedIn", href: "https://www.linkedin.com/feed/" },
  ],
  projects: [
    {
      year: "2026",
      title: "Sales Dashboard",
      type: "Product Design / Next.js",
      desc: "A comprehensive sales dashboard built with modern web technologies, designed to provide insights and analytics for sales performance.",
      tags: ["React", "Next.js", "GSAP", "Maps", "Node.js", "Express.JS", "Postgres", "Drizzle ORM", "Zod", "S3"],
      accent: "#7dd3fc",
      image: "/projects/sales-dashboard.png",
      liveUrl: "https://sales.ellwaa.com/",
      frontendRepo: "https://github.com/ellwaa-org/ellwaa-sales-dashboard-frontend",
      backendRepo: "https://github.com/ellwaa-org/ellwaa-sales-dashboard-backend",
    },
    {
      year: "2026",
      title: "Whatsapp Instance",
      type: "Product Design / Next.js",
      desc: "WhatsApp Instances Desktop App is a desktop application built with TypeScript for managing multiple WhatsApp instances from a single interface.",
      tags: ["React", "Electron", "Tailwind", "Typescript", "Desktop Application"],
      accent: "#7dd3fc",
      image: "/projects/whats-app-instances.png",
      frontendRepo: "https://github.com/ellwaa-org/whatsapp-instances-destop-app",
      backendRepo: "https://github.com/ellwaa-org/whatsapp-instances-destop-app",
    },
    {
      year: "2026",
      title: "Internal HR System",
      type: "Product Design / Next.js",
      desc: "A comprehensive internal HR system built with modern web technologies, designed to streamline employee management, onboarding, and communication within an organization.",
      tags: ["React", "Next.js", "GSAP", "Maps", "Node.js", "Express.JS", "Postgres", "Drizzle ORM", "Zod", "S3"],
      accent: "#7dd3fc",
      image: "/projects/internal-hr-system.png",
      liveUrl: "https://hr-staging.ellwaa.com",
      frontendRepo: "https://github.com/ellwaa-org/internal-hr-frontend",
      backendRepo: "https://github.com/ellwaa-org/internal-hr-backend",
    },
    {
      year: "2026",
      title: "Wedding App",
      type: "Product Design / Next.js",
      desc: "Wedding invitation site for Yasmin and Omar, centered on a single polished landing page that presents the couple’s story, event details, itinerary, venue, registry, FAQs, and RSVP footer. It’s a front-end experience rather than a data-heavy app: mostly static content.",
      tags: ["React", "Next.js", "GSAP", "Maps"],
      accent: "#7dd3fc",
      image: "/projects/wedding-site.png",
      liveUrl: "https://yasmin-omar-wedding.vercel.app/",
      frontendRepo: "https://github.com/yousseffninja/wedding-site",
      backendRepo: "https://github.com/yousseffninja/wedding-site",
    },
    {
      year: "2026",
      title: "Nexus - Game Store",
      type: "Product Design / Next.js",
      desc: "A multi-locale React dashboard with authentication and a protected dashboard area, intended to be deployed to Vercel and used by end users/administrators to interact with the Nexus Gold backend.",
      tags: ["React", "Next", "Tailwind", "TypeScript", "Vercel"],
      accent: "#7dd3fc",
      image: "/projects/nexus.png",
      liveUrl: "https://nexus-gold-forntend.vercel.app/en/home",
      frontendRepo: "https://github.com/yousseffninja/nexus-gold-forntend",
      backendRepo: "https://github.com/yousseffninja/nexus-gold",
    },
    {
      year: "2026",
      title: "jobflow - ATS Calculator",
      type: "Brand Site",
      desc: "JobFlow Frontend — a TypeScript Next.js (App Router) frontend for a job/dashboard platform providing auth, job listings/workflows, bilingual UI (EN/AR), real-time notifications, and small AI integrations",
      tags: ["React", "Next", "Tailwind", "TypeScript", "Vercel"],
      accent: "#c4b5fd",
      image: "/projects/jobflow.png",
      liveUrl: "https://jobflow-frontend-ten.vercel.app/",
      frontendRepo: "https://github.com/yousseffninja/jobflow-frontend",
      backendRepo: "https://github.com/yousseffninja/jobflow-backend",
    },
    {
      year: "2023",
      title: "Locom Frontend App",
      type: "Next.js Frontend",
      desc: "A Next.js + TypeScript frontend (bootstrapped with create-next-app) for the Locom project. Uses React, MUI, TailwindCSS, and styled-components and is deployed on Vercel.",
      tags: ["Next.js", "TypeScript", "React", "MUI", "Tailwind", "Vercel"],
      accent: "#86efac",
      image: "/projects/locom.png",
      liveUrl: "https://locom-frontend-app.vercel.app/",
      frontendRepo: "https://github.com/yousseffninja/locom-frontend-app",
      backendRepo: "https://github.com/yousseffninja/locom-frontend-app",
    },
    {
      year: "2024",
      title: "A3maly Dashboard",
      type: "Design System",
      desc: "A lighting-aware component kit. Tokens for glow, blur, and elevation used across three product surfaces.",
      tags: ["Design Tokens", "Docs", "React"],
      accent: "#fcd34d",
      image: "/projects/a3maly.png",
      liveUrl: "https://a3maly-web.vercel.app",
      frontendRepo: "https://github.com/yousseffninja/a3maly-web",
      backendRepo: "https://github.com/yousseffninja/a3maly-web",
    },
  ],
  skills: [
    "Next.js",
    "React",
    "TypeScript",
    "GSAP",
    "ScrollTrigger",
    "Tailwind",
    "Framer Motion",
    "Node.js",
    "Figma",
    "Accessibility",
    "Performance",
    "Design Systems",
  ],
  previousWork: [
    {
      company: "El-Lwaa Law Firm",
      role: "Full-Stack Engineer",
      period: "Oct 2026 — Present",
      location: "Cairo",
      desc: "Developed and maintained scalable full-stack web applications using React, Next.js, Node.js, and TypeScript. Built RESTful APIs, implemented authentication and database solutions, optimized application performance with Redis and efficient state management, and delivered responsive, user-friendly interfaces using Tailwind CSS and MUI.",
      tags: [
        "React.js",
        "Next.js",
        "TypeScript",
        "Node.js",
        "Express.js",
        "REST APIs",
        "PostgreSQL",
        "MongoDB",
        "Redis",
        "Docker",
        "Tailwind CSS",
        "MUI",
        "React Query",
        "Authentication",
        "API Integration",
        "Performance Optimization"
      ]
    },
    {
      company: "SalamDev",
      role: "Full-Stack Engineer",
      period: "Apr 2025 — Apr 2026",
      location: "Remote - Canada",
      desc: "Developed scalable user-facing features with Next.js and TypeScript, implementing secure authentication with Supabase Auth and Persona identity verification. Integrated Stripe for subscriptions and driver payouts, optimized data fetching with React Query and Context API, and built responsive interfaces with Tailwind CSS. Improved performance through lazy loading, code splitting, and memoization.",
      tags: [
        "Next.js",
        "TypeScript",
        "Supabase Auth",
        "Persona",
        "Stripe",
        "Stripe Connect",
        "React Query",
        "Context API",
        "Tailwind CSS",
        "Authentication",
        "Identity Verification",
        "Subscription Management",
        "Payment Integration",
        "Lazy Loading",
        "Code Splitting",
        "Memoization"
      ],
    },
    {
      company: "Hex Soft Solution",
      role: "Full-Stack Engineer",
      period: "Aug 2023 — Jan 2024",
      location: "Remote",
      desc: "Developed full-stack web applications using the MERN stack, with Redis for performance optimization and middleware integration. Built responsive interfaces using React, MUI, and Tailwind CSS, and implemented database modeling, authentication, and real-time data handling with Firebase.",
      tags: [
        "MongoDB",
        "Express.js",
        "React.js",
        "Node.js",
        "Redis",
        "MUI",
        "Tailwind CSS",
        "Firebase",
        "REST APIs",
        "Authentication",
        "Database Modeling",
        "Real-time Data"
      ],
    },
    {
      company: "Alexs Apps",
      role: "Frontend Engineer",
      period: "Mar 2023 — Aug 2023",
      location: "Remote",
      desc: "Developed high-performance, responsive web applications using React.js and Next.js, optimizing load times and scalability with SSR, lazy loading, and efficient state management. Built pixel-perfect UIs with MUI and Tailwind CSS and integrated RESTful APIs using Axios and React Query.",
      tags: ["React.js", "Next.js", "JavaScript", "UI", "MUI", "Tailwind CSS", "Axios", "React Query"],
    },
  ],
};
