export const site = {
  name: "Youssef Saleh",
  role: "Software Engineer",
  brief:
    "Full-Stack Developer skilled in React.js, Next.js, Node.js, NestJS, and Java Spring Boot, experienced in building scalable web applications, REST APIs, and responsive UIs with clean, maintainable code.",
  email: "hello@alexhart.dev",
  location: "Remote / Europe",
  availability: "Open for select projects",
  nav: [
    { label: "Work", href: "#work" },
    { label: "Previous", href: "#previous" },
    { label: "About", href: "#about" },
    { label: "Skills", href: "#skills" },
    { label: "Contact", href: "#contact" },
  ],
  socials: [
    { label: "GitHub", href: "https://github.com" },
    { label: "LinkedIn", href: "https://linkedin.com" },
    { label: "X", href: "https://x.com" },
  ],
  projects: [
    {
      year: "2026",
      title: "Northline",
      type: "Product Design / Next.js",
      desc: "A calm operations console for logistics teams. Motion-first UI, live maps, and a light system that reacts to status.",
      tags: ["Next.js", "GSAP", "Maps"],
      accent: "#7dd3fc",
      image: "/projects/northline.jpg",
    },
    {
      year: "2025",
      title: "Atelier",
      type: "Brand Site",
      desc: "Editorial portfolio for a photography studio. Slow scroll, film-grain light, and image reveals that feel analog.",
      tags: ["React", "Scroll", "CMS"],
      accent: "#c4b5fd",
      image: "/projects/atelier.jpg",
    },
    {
      year: "2023",
      title: "Locom Frontend App",
      type: "Next.js Frontend",
      desc: "A Next.js + TypeScript frontend (bootstrapped with create-next-app) for the Locom project. Uses React, MUI, TailwindCSS, and styled-components and is deployed on Vercel.",
      tags: ["Next.js", "TypeScript", "React", "MUI", "Tailwind", "Vercel"],
      accent: "#86efac",
      image: "/projects/locom.png",
    },
    {
      year: "2024",
      title: "A3maly Dashboard",
      type: "Design System",
      desc: "A lighting-aware component kit. Tokens for glow, blur, and elevation used across three product surfaces.",
      tags: ["Design Tokens", "Docs", "React"],
      accent: "#fcd34d",
      image: "/projects/a3maly.png",
    },
  ],
  skills: [
    "Next.js",
    "React",
    "TypeScript",
    "GSAP",
    "ScrollTrigger",
    "Tailwind",
    "Framer Motion",
    "Node.js",
    "Figma",
    "Accessibility",
    "Performance",
    "Design Systems",
  ],
  previousWork: [
    {
      company: "El-Lwaa Law Firm",
      role: "Full-Stack Engineer",
      period: "Oct 2026 — Present",
      location: "Cairo",
      desc: "Developed and maintained scalable full-stack web applications using React, Next.js, Node.js, and TypeScript. Built RESTful APIs, implemented authentication and database solutions, optimized application performance with Redis and efficient state management, and delivered responsive, user-friendly interfaces using Tailwind CSS and MUI.",
      tags: [
        "React.js",
        "Next.js",
        "TypeScript",
        "Node.js",
        "Express.js",
        "REST APIs",
        "PostgreSQL",
        "MongoDB",
        "Redis",
        "Docker",
        "Tailwind CSS",
        "MUI",
        "React Query",
        "Authentication",
        "API Integration",
        "Performance Optimization"
      ]
    },
    {
      company: "SalamDev",
      role: "Full-Stack Engineer",
      period: "Apr 2025 — Oct 2025",
      location: "Remote - Canada",
      desc: "Developed scalable user-facing features with Next.js and TypeScript, implementing secure authentication with Supabase Auth and Persona identity verification. Integrated Stripe for subscriptions and driver payouts, optimized data fetching with React Query and Context API, and built responsive interfaces with Tailwind CSS. Improved performance through lazy loading, code splitting, and memoization.",
      tags: [
        "Next.js",
        "TypeScript",
        "Supabase Auth",
        "Persona",
        "Stripe",
        "Stripe Connect",
        "React Query",
        "Context API",
        "Tailwind CSS",
        "Authentication",
        "Identity Verification",
        "Subscription Management",
        "Payment Integration",
        "Lazy Loading",
        "Code Splitting",
        "Memoization"
      ],
    },
    {
      company: "Al-Manara Tech",
      role: "React-Native Developer",
      period: "Jun 2025 — Mar 2025",
      location: "Cairo",
      desc: "Built cross-platform mobile applications with React Native, integrating Firebase Authentication, Firestore, and Realtime Database. Implemented push notifications, real-time data synchronization, and offline capabilities while focusing on performance and responsive user experiences.",
      tags: [
        "React Native",
        "Firebase",
        "Firebase Authentication",
        "Firestore",
        "Realtime Database",
        "Push Notifications",
        "Real-time Data",
        "Data Synchronization",
        "Offline Support",
        "Responsive Design"
      ],
    },
    {
      company: "Hex Soft Solution",
      role: "Full-Stack Engineer",
      period: "Aug 2023 — Oct 2023",
      location: "Remote",
      desc: "Developed full-stack web applications using the MERN stack, with Redis for performance optimization and middleware integration. Built responsive interfaces using React, MUI, and Tailwind CSS, and implemented database modeling, authentication, and real-time data handling with Firebase.",
      tags: [
        "MongoDB",
        "Express.js",
        "React.js",
        "Node.js",
        "Redis",
        "MUI",
        "Tailwind CSS",
        "Firebase",
        "REST APIs",
        "Authentication",
        "Database Modeling",
        "Real-time Data"
      ],
    },
    {
      company: "Alexs Apps",
      role: "Frontend Engineer",
      period: "Mar 2023 — Aug 2023",
      location: "Remote",
      desc: "Developed high-performance, responsive web applications using React.js and Next.js, optimizing load times and scalability with SSR, lazy loading, and efficient state management. Built pixel-perfect UIs with MUI and Tailwind CSS and integrated RESTful APIs using Axios and React Query.",
      tags: ["React.js", "Next.js", "JavaScript", "UI", "MUI", "Tailwind CSS", "Axios", "React Query"],
    },
  ],
};
