export const site = {
  name: "Youssef Saleh",
  role: "Software Engineer",
  brief:
    "Full-Stack Developer skilled in React.js, Next.js, Node.js, NestJS, and Java Spring Boot, experienced in building scalable web applications, REST APIs, and responsive UIs with clean, maintainable code.",
  email: "hello@alexhart.dev",
  location: "Remote / Europe",
  availability: "Open for select projects",
  nav: [
    { label: "Work", href: "#work" },
    { label: "About", href: "#about" },
    { label: "Skills", href: "#skills" },
    { label: "Contact", href: "#contact" },
  ],
  socials: [
    { label: "GitHub", href: "https://github.com" },
    { label: "LinkedIn", href: "https://linkedin.com" },
    { label: "X", href: "https://x.com" },
  ],
  projects: [
    {
      year: "2026",
      title: "Northline",
      type: "Product Design / Next.js",
      desc: "A calm operations console for logistics teams. Motion-first UI, live maps, and a light system that reacts to status.",
      tags: ["Next.js", "GSAP", "Maps"],
      accent: "#7dd3fc",
    },
    {
      year: "2025",
      title: "Atelier",
      type: "Brand Site",
      desc: "Editorial portfolio for a photography studio. Slow scroll, film-grain light, and image reveals that feel analog.",
      tags: ["React", "Scroll", "CMS"],
      accent: "#c4b5fd",
    },
    {
      year: "2025",
      title: "Pulse Lab",
      type: "SaaS Dashboard",
      desc: "Health analytics with a dark glass interface. Charts, filters, and micro-interactions that stay out of the way.",
      tags: ["TypeScript", "Charts", "A11y"],
      accent: "#86efac",
    },
    {
      year: "2024",
      title: "Lumen OS",
      type: "Design System",
      desc: "A lighting-aware component kit. Tokens for glow, blur, and elevation used across three product surfaces.",
      tags: ["Design Tokens", "Docs", "React"],
      accent: "#fcd34d",
    },
  ],
  skills: [
    "Next.js",
    "React",
    "TypeScript",
    "GSAP",
    "ScrollTrigger",
    "Tailwind",
    "Framer Motion",
    "Node.js",
    "Figma",
    "Accessibility",
    "Performance",
    "Design Systems",
  ],
};
